name: 🚀 Deploy via FTP

on:
  push:
    branches:
      - main  # Ganti kalau branch utamamu bukan "main"

jobs:
  ftp-deploy:
    name: 📂 Upload to Hosting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: 📤 Deploy files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/     # Ganti jika subdomain kamu di folder lain
